name: Release

# release on push version tag, e.g. v0.3.2
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

env:
  PYTHON_VERSION: 3.11

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        run: python -m pip install --upgrade pip poetry

      - name: Install build tools
        run: python -m pip install build twine

      - name: Check if tag matches the package version
        run: |
          PKG_VERSION=$(poetry version -s)
          TAG=${GITHUB_REF#refs/tags/}
          if [[ "v$PKG_VERSION" != "$TAG" ]]; then
            echo "Error: Tag ($TAG) does not match the package version (v$PKG_VERSION)."
            exit 1
          fi

      - name: Build sdist and universal wheel
        run: python -m build --sdist --wheel --outdir dist

      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: "dist/*"

      - name: Publish to PyPI if not already published
        env:
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          PKG_VERSION=$(poetry version -s)
          PKG_NAME=$(poetry version | awk '{print $1}')
          if curl -sSf https://pypi.org/pypi/$PKG_NAME/json | grep -q "\"$PKG_VERSION\""; then
            echo "Version $PKG_VERSION already exists on PyPI. Skipping publish."
          else
            twine upload --skip-existing dist/*
          fi
